name: Build Go

on:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  # release:
  #   types: [created]
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Bump tag type: major, minor, patch. default: minor'
        required: true
        default: 'minor'

jobs:
  go-build:
    runs-on: ubuntu-latest
    name: go build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Environment
        run: |
          go mod tidy
      - name: Bump tag version
        id: bumpTag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
          DEFAULT_BUMP: "${{ github.event.inputs.bump_type }}" 
      - name: Bump tag locally
        run: git tag ${{ steps.bumpTag.outputs.new_tag }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
